### ISSUE TITLE
运行的时候提示api无效？

### ISSUE THREAD

**Issue by zhongqian** [thggdx/NeteaseMusicDownload#2]
当前工作路径: D:\pythonObject
请输入API地址(可跳过):
API无效
程序异常退出
-----------
单独打开api的地址也打不开，网络问题？
https://ncm-api.thggdx.eu.org/

**Comment by thggdx** [comment]
网络问题，移动网络间歇性阻断，部分地区跳反诈。
解决办法：切换网络环境、使用代理、自行部署api
